name: Check
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 64
    - name: Run checkpatch.pl
      run: ./.ci-check.sh HEAD~1
